A collection of from-scratch implementations of various basic machine learning algorithms and metrics for evaluating algorithms.

In [2]:
import numpy as np

# Evaluation Metrics #

Implementating various useful metrics for evaluating machine learning models. Should include metrics for classification (binary and multilabel) and regression.

In [18]:
# entry i,j is the true label i labeled j
def confusion_matrix(y_true, y_pred):
    # get class labels in this data set
    unique = list(set(y_true))
    unique.sort()
    num_classes = len(unique)
    
    # create and fill out confusion matrix
    cmatrix = np.zeros((num_classes, num_classes))
    
    for i in range(len(y_true)):
        true = unique.index(y_true[i])
        pred = unique.index(y_pred[i])
        cmatrix[true][pred] += 1
    
    return cmatrix

# returns true positives for each class
# true positive: actual and predicted this class
def get_true_positives(y_true, y_pred, cmatrix=None):
    tp = []
    
    if cmatrix is not None:
        tp = np.diagonal(cmatrix)
        
    else:
        y_true = np.asarray(y_true)
        y_pred = np.asarray(y_pred)
        
        # get list of classes 
        unique = list(set(y_true))
        unique.sort()
        
        for u in unique:
            tmp = np.sum(np.logical_and(y_true == u, y_pred == u))
            tp.append(tmp)
    
    # in binary case, treat first label as the positive
    if len(tp) == 2:
        return tp[0]
                
    return tp

# return true negatives for each class
# true negative: actual and predicted are not of this class
def get_true_negatives(y_true, y_pred, cmatrix=None):
    tn = []
    
    if cmatrix is not None:
        # get false negatives and false positives for each
        # would double count true positives though, so arbitrarily subtract from one
        fn = np.sum(cmatrix, axis=1)
        fp = np.sum(cmatrix, axis=0) - np.diagonal(cmatrix)
        
        # get the total in the entire matrix
        total = np.sum(fn)
        
        tn = total - (fn + fp)
            
    else:
        unique = list(set(y_true))
        unique.sort()
        
        y_true = np.asarray(y_true)
        y_pred = np.asarray(y_pred)
        
        for u in unique:
            tmp = np.sum(np.logical_and(y_true != u, y_pred != u))
            tn.append(tmp)
    
    # in binary case, treat second label as negative
    if len(tn) == 2:
        return tn[1]
    
    return tn

# returns false positives for each class
# false positive: predicted this class, not actually this class
def get_false_positives(y_true, y_pred, cmatrix=None):
    fp = []
    
    if cmatrix is not None:
        fp = np.sum(cmatrix, axis=0) - np.diagonal(cmatrix)
        
    else:
        unique = list(set(y_true))
        unique.sort()
        
        y_true = np.asarray(y_true)
        y_pred = np.asarray(y_pred)
                
        for u in unique:
            tmp = np.sum(np.logical_and(y_true != u, y_pred == u))
            fp.append(tmp)
    
    # in binary case, treat first label as positive
    if len(fp) == 2:
        return fp[0]
    
    return fp

# returns false negatives for each class
# false negative: actual this class, not predicted this class
def get_false_negatives(y_true, y_pred, cmatrix=None):
    fn = []
    
    if cmatrix is not None:
        fn = np.sum(cmatrix, axis=1) - np.diagonal(cmatrix)
    
    else:
        unique = list(set(y_true))
        unique.sort()
        
        y_true = np.asarray(y_true)
        y_pred = np.asarray(y_pred)
        
        for u in unique:
            tmp = np.sum(np.logical_and(y_true == u, y_pred != u))
            fn.append(tmp)
    
    # in binary case, treat second label as negative
    if len(fn) == 2:
        return fn[1]
    
    return fn

# TP / all
def accuracy(y_true, y_pred, cmatrix=None):
    tps = np.asarray(get_true_positives(y_true, y_pred, cmatrix))
    total = len(y_true)
    
    return np.sum(tps)/total
    
# returns for each class
# TP / (TP + FN)
def recall(y_true, y_pred, cmatrix=None):
    tps = np.asarray(get_true_positives(y_true, y_pred, cmatrix))
    fns = np.asarray(get_false_negatives(y_true, y_pred, cmatrix))
    
    recall = tps / (tps+fns)
    
    return recall

# returns for each class
# TP / (TP + FP)
def precision(y_true, y_pred, cmatrix=None):
    tps = np.asarray(get_true_positives(y_true, y_pred, cmatrix))
    fps = np.asarray(get_false_positives(y_true, y_pred, cmatrix))
    
    prec = tps / (tps + fps)
    
    return prec

# returns for each class
# 2 * (precision * recall / precision + recall)
def f1_score(y_true, y_pred, cmatrix=None):
    prec = precision(y_true, y_pred, cmatrix)
    rec = recall(y_true, y_pred, cmatrix)
    
    f1 = 2*((prec*rec)/(prec+rec))
    
    return f1

# calculate root mean squared error for regression problems
def calc_rms(y_true, y_pred):
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)
    
    tmp = np.square(y_pred - y_true)
    tmp = np.sum(tmp)/len(y_pred)
    
    return tmp**(1/2)



[[3. 1. 0.]
 [1. 2. 1.]
 [1. 1. 2.]]

true positives
[3, 2, 2]
false positives
cmatrix: [2. 2. 1.]
false negatives
cmatrix: [1. 2. 2.]
true negatives
cmatrix: [6. 6. 7.]

recall: [0.75 0.5  0.5 ]
precision: [0.6        0.5        0.66666667]
f1: [0.66666667 0.5        0.57142857]
accuracy: 0.5833333333333334
rms: 1.002496882788171
